import type { CategoryConfig } from "@/shared/types";

/**
 * Per-category configuration — PRD section 4.4
 * Controls matching thresholds, routing queues, and extraction schemas.
 */
export const CATEGORY_CONFIG: CategoryConfig[] = [
  {
    category: "lab",
    label: "Lab Results",
    confident_match_threshold: 0.95,
    review_threshold: 0.70,
    always_human_review: false,
    route_to_queue: "labs_review",
    splittable: false,
    schema_key: "lab_result",
    component_weights: {
      identifier_exact: 0.35,
      family_name: 0.15,
      given_name: 0.10,
      middle_name: 0.05,
      dob_exact: 0.25,
      sex: 0.02,
      postal_code: 0.03,
      street_fuzzy: 0.02,
      phone_match: 0.02,
      insurance_member_id: 0.00,
      alias_match: 0.01,
    },
  },
  {
    category: "imaging",
    label: "Imaging Report",
    confident_match_threshold: 0.95,
    review_threshold: 0.70,
    always_human_review: false,
    route_to_queue: "imaging_review",
    splittable: false,
    schema_key: "imaging_report",
    component_weights: {
      identifier_exact: 0.35,
      family_name: 0.15,
      given_name: 0.10,
      middle_name: 0.05,
      dob_exact: 0.25,
      sex: 0.02,
      postal_code: 0.03,
      street_fuzzy: 0.02,
      phone_match: 0.02,
      insurance_member_id: 0.00,
      alias_match: 0.01,
    },
  },
  {
    category: "consult",
    label: "Consult Note",
    confident_match_threshold: 0.97,
    review_threshold: 0.80,
    always_human_review: true,
    route_to_queue: "clinical_review",
    splittable: false,
    schema_key: "consult_note",
    component_weights: {
      identifier_exact: 0.30,
      family_name: 0.15,
      given_name: 0.10,
      middle_name: 0.05,
      dob_exact: 0.25,
      sex: 0.02,
      postal_code: 0.03,
      street_fuzzy: 0.02,
      phone_match: 0.02,
      insurance_member_id: 0.05,
      alias_match: 0.01,
    },
  },
  {
    category: "referral",
    label: "Referral",
    confident_match_threshold: 1.01, // never auto-confident
    review_threshold: 0.70,
    always_human_review: true,
    route_to_queue: "front_desk",
    splittable: false,
    schema_key: "referral_incoming",
    component_weights: {
      identifier_exact: 0.30,
      family_name: 0.15,
      given_name: 0.10,
      middle_name: 0.05,
      dob_exact: 0.25,
      sex: 0.02,
      postal_code: 0.03,
      street_fuzzy: 0.02,
      phone_match: 0.02,
      insurance_member_id: 0.05,
      alias_match: 0.01,
    },
  },
  {
    category: "prior_auth",
    label: "Prior Auth",
    confident_match_threshold: 1.01,
    review_threshold: 0.80,
    always_human_review: true,
    route_to_queue: "billing_review",
    splittable: false,
    schema_key: "prior_auth_response",
    component_weights: {
      identifier_exact: 0.30,
      family_name: 0.15,
      given_name: 0.10,
      middle_name: 0.05,
      dob_exact: 0.20,
      sex: 0.00,
      postal_code: 0.03,
      street_fuzzy: 0.00,
      phone_match: 0.00,
      insurance_member_id: 0.15,
      alias_match: 0.02,
    },
  },
  {
    category: "dme",
    label: "DME",
    confident_match_threshold: 0.95,
    review_threshold: 0.75,
    always_human_review: false,
    route_to_queue: "front_desk",
    splittable: false,
    schema_key: "dme_documentation",
    component_weights: {
      identifier_exact: 0.30,
      family_name: 0.15,
      given_name: 0.10,
      middle_name: 0.05,
      dob_exact: 0.25,
      sex: 0.02,
      postal_code: 0.03,
      street_fuzzy: 0.02,
      phone_match: 0.02,
      insurance_member_id: 0.05,
      alias_match: 0.01,
    },
  },
  {
    category: "forms",
    label: "Forms",
    confident_match_threshold: 0.95,
    review_threshold: 0.70,
    always_human_review: false,
    route_to_queue: "front_desk",
    splittable: false,
    schema_key: "physical_exam_form",
    component_weights: {
      identifier_exact: 0.30,
      family_name: 0.15,
      given_name: 0.10,
      middle_name: 0.05,
      dob_exact: 0.25,
      sex: 0.02,
      postal_code: 0.03,
      street_fuzzy: 0.02,
      phone_match: 0.02,
      insurance_member_id: 0.05,
      alias_match: 0.01,
    },
  },
  {
    category: "records_request",
    label: "Records Request",
    confident_match_threshold: 0.97,
    review_threshold: 0.80,
    always_human_review: true,
    route_to_queue: "front_desk",
    splittable: false,
    schema_key: "medical_records_request",
    component_weights: {
      identifier_exact: 0.30,
      family_name: 0.15,
      given_name: 0.10,
      middle_name: 0.05,
      dob_exact: 0.25,
      sex: 0.02,
      postal_code: 0.03,
      street_fuzzy: 0.02,
      phone_match: 0.02,
      insurance_member_id: 0.05,
      alias_match: 0.01,
    },
  },
  {
    category: "eob",
    label: "EOB / ERA",
    confident_match_threshold: 0.99,
    review_threshold: 0.85,
    always_human_review: false,
    route_to_queue: "billing_review",
    splittable: true,
    schema_key: "eob_era",
    component_weights: {
      identifier_exact: 0.10,
      family_name: 0.15,
      given_name: 0.10,
      middle_name: 0.02,
      dob_exact: 0.20,
      sex: 0.00,
      postal_code: 0.03,
      street_fuzzy: 0.00,
      phone_match: 0.00,
      insurance_member_id: 0.38,
      alias_match: 0.02,
    },
  },
  {
    category: "discharge",
    label: "Discharge Summary",
    confident_match_threshold: 0.95,
    review_threshold: 0.75,
    always_human_review: true,
    route_to_queue: "nurse_triage",
    splittable: false,
    schema_key: "hospital_discharge_summary",
    component_weights: {
      identifier_exact: 0.30,
      family_name: 0.15,
      given_name: 0.10,
      middle_name: 0.05,
      dob_exact: 0.25,
      sex: 0.02,
      postal_code: 0.03,
      street_fuzzy: 0.02,
      phone_match: 0.02,
      insurance_member_id: 0.05,
      alias_match: 0.01,
    },
  },
  {
    category: "other",
    label: "Other / Unclassified",
    confident_match_threshold: 1.01,
    review_threshold: 0.70,
    always_human_review: true,
    route_to_queue: "front_desk",
    splittable: false,
    schema_key: "unclassified",
    component_weights: {
      identifier_exact: 0.30,
      family_name: 0.15,
      given_name: 0.10,
      middle_name: 0.05,
      dob_exact: 0.25,
      sex: 0.02,
      postal_code: 0.03,
      street_fuzzy: 0.02,
      phone_match: 0.02,
      insurance_member_id: 0.05,
      alias_match: 0.01,
    },
  },
];

export function getCategoryConfig(category: string): CategoryConfig | undefined {
  return CATEGORY_CONFIG.find((c) => c.category === category);
}
