import type { CategoryConfig } from "@/shared/types";

/** Default weights shared by most categories */
const DEFAULT_WEIGHTS = {
  identifier_exact: 0.30,
  family_name: 0.15,
  given_name: 0.10,
  middle_name: 0.05,
  dob_exact: 0.25,
  sex: 0.02,
  postal_code: 0.03,
  street_fuzzy: 0.02,
  phone_match: 0.02,
  insurance_member_id: 0.05,
  alias_match: 0.01,
};

/** Lab-heavy weights (MRN/identifier matters more) */
const LAB_WEIGHTS = {
  ...DEFAULT_WEIGHTS,
  identifier_exact: 0.35,
  insurance_member_id: 0.00,
};

/** Billing-heavy weights (insurance ID matters more) */
const BILLING_WEIGHTS = {
  ...DEFAULT_WEIGHTS,
  identifier_exact: 0.10,
  insurance_member_id: 0.38,
  street_fuzzy: 0.00,
  phone_match: 0.00,
  sex: 0.00,
  dob_exact: 0.20,
  middle_name: 0.02,
};

/**
 * Full 25-category configuration matching the JSON schemas in src/data/schemas/.
 * Each entry's `category` matches the schema filename and sidebar slug.
 */
export const CATEGORY_CONFIG: CategoryConfig[] = [
  {
    category: "lab_result",
    label: "Lab Results",
    confident_match_threshold: 0.95,
    review_threshold: 0.70,
    always_human_review: false,
    route_to_queue: "labs_review",
    splittable: false,
    schema_key: "lab_result",
    component_weights: LAB_WEIGHTS,
  },
  {
    category: "imaging_report",
    label: "Imaging Report",
    confident_match_threshold: 0.95,
    review_threshold: 0.70,
    always_human_review: false,
    route_to_queue: "imaging_review",
    splittable: false,
    schema_key: "imaging_report",
    component_weights: LAB_WEIGHTS,
  },
  {
    category: "consult_note",
    label: "Consult Note",
    confident_match_threshold: 0.97,
    review_threshold: 0.80,
    always_human_review: true,
    route_to_queue: "clinical_review",
    splittable: false,
    schema_key: "consult_note",
    component_weights: DEFAULT_WEIGHTS,
  },
  {
    category: "referral_incoming",
    label: "Incoming Referral",
    confident_match_threshold: 1.01,
    review_threshold: 0.70,
    always_human_review: true,
    route_to_queue: "front_desk",
    splittable: false,
    schema_key: "referral_incoming",
    component_weights: DEFAULT_WEIGHTS,
  },
  {
    category: "prior_auth_response",
    label: "Prior Auth Response",
    confident_match_threshold: 1.01,
    review_threshold: 0.80,
    always_human_review: true,
    route_to_queue: "billing_review",
    splittable: false,
    schema_key: "prior_auth_response",
    component_weights: { ...DEFAULT_WEIGHTS, insurance_member_id: 0.15, identifier_exact: 0.30, dob_exact: 0.20, phone_match: 0.00, street_fuzzy: 0.00, sex: 0.00 },
  },
  {
    category: "pharmacy_prior_auth_request",
    label: "Pharmacy Prior Auth",
    confident_match_threshold: 1.01,
    review_threshold: 0.80,
    always_human_review: true,
    route_to_queue: "billing_review",
    splittable: false,
    schema_key: "pharmacy_prior_auth_request",
    component_weights: { ...DEFAULT_WEIGHTS, insurance_member_id: 0.15, identifier_exact: 0.30, dob_exact: 0.20, phone_match: 0.00, street_fuzzy: 0.00, sex: 0.00 },
  },
  {
    category: "pharmacy_refill_request",
    label: "Rx Refill Request",
    confident_match_threshold: 0.95,
    review_threshold: 0.70,
    always_human_review: false,
    route_to_queue: "clinical_review",
    splittable: false,
    schema_key: "pharmacy_refill_request",
    component_weights: DEFAULT_WEIGHTS,
  },
  {
    category: "dme_documentation",
    label: "DME Documentation",
    confident_match_threshold: 0.95,
    review_threshold: 0.75,
    always_human_review: false,
    route_to_queue: "front_desk",
    splittable: false,
    schema_key: "dme_documentation",
    component_weights: DEFAULT_WEIGHTS,
  },
  {
    category: "physical_exam_form",
    label: "Physical Exam Form",
    confident_match_threshold: 0.95,
    review_threshold: 0.70,
    always_human_review: false,
    route_to_queue: "front_desk",
    splittable: false,
    schema_key: "physical_exam_form",
    component_weights: DEFAULT_WEIGHTS,
  },
  {
    category: "medical_records_request",
    label: "Records Request",
    confident_match_threshold: 0.97,
    review_threshold: 0.80,
    always_human_review: true,
    route_to_queue: "front_desk",
    splittable: false,
    schema_key: "medical_records_request",
    component_weights: DEFAULT_WEIGHTS,
  },
  {
    category: "eob_era",
    label: "EOB / ERA",
    confident_match_threshold: 0.99,
    review_threshold: 0.85,
    always_human_review: false,
    route_to_queue: "billing_review",
    splittable: true,
    schema_key: "eob_era",
    component_weights: BILLING_WEIGHTS,
  },
  {
    category: "hospital_discharge_summary",
    label: "Discharge Summary",
    confident_match_threshold: 0.95,
    review_threshold: 0.75,
    always_human_review: true,
    route_to_queue: "nurse_triage",
    splittable: false,
    schema_key: "hospital_discharge_summary",
    component_weights: DEFAULT_WEIGHTS,
  },
  {
    category: "ed_visit_summary",
    label: "ED Visit Summary",
    confident_match_threshold: 0.95,
    review_threshold: 0.75,
    always_human_review: true,
    route_to_queue: "nurse_triage",
    splittable: false,
    schema_key: "ed_visit_summary",
    component_weights: DEFAULT_WEIGHTS,
  },
  {
    category: "cardiac_diagnostic_report",
    label: "Cardiac Diagnostic",
    confident_match_threshold: 0.95,
    review_threshold: 0.70,
    always_human_review: false,
    route_to_queue: "labs_review",
    splittable: false,
    schema_key: "cardiac_diagnostic_report",
    component_weights: LAB_WEIGHTS,
  },
  {
    category: "pathology_report",
    label: "Pathology Report",
    confident_match_threshold: 0.95,
    review_threshold: 0.70,
    always_human_review: true,
    route_to_queue: "labs_review",
    splittable: false,
    schema_key: "pathology_report",
    component_weights: LAB_WEIGHTS,
  },
  {
    category: "immunization_record",
    label: "Immunization Record",
    confident_match_threshold: 0.95,
    review_threshold: 0.70,
    always_human_review: false,
    route_to_queue: "front_desk",
    splittable: false,
    schema_key: "immunization_record",
    component_weights: DEFAULT_WEIGHTS,
  },
  {
    category: "home_health_order",
    label: "Home Health Order",
    confident_match_threshold: 0.95,
    review_threshold: 0.75,
    always_human_review: true,
    route_to_queue: "clinical_review",
    splittable: false,
    schema_key: "home_health_order",
    component_weights: DEFAULT_WEIGHTS,
  },
  {
    category: "hospice_correspondence",
    label: "Hospice Correspondence",
    confident_match_threshold: 0.95,
    review_threshold: 0.75,
    always_human_review: true,
    route_to_queue: "clinical_review",
    splittable: false,
    schema_key: "hospice_correspondence",
    component_weights: DEFAULT_WEIGHTS,
  },
  {
    category: "snf_nh_correspondence",
    label: "SNF/NH Correspondence",
    confident_match_threshold: 0.95,
    review_threshold: 0.75,
    always_human_review: true,
    route_to_queue: "clinical_review",
    splittable: false,
    schema_key: "snf_nh_correspondence",
    component_weights: DEFAULT_WEIGHTS,
  },
  {
    category: "disability_or_leave_form",
    label: "Disability/Leave Form",
    confident_match_threshold: 0.95,
    review_threshold: 0.70,
    always_human_review: false,
    route_to_queue: "front_desk",
    splittable: false,
    schema_key: "disability_or_leave_form",
    component_weights: DEFAULT_WEIGHTS,
  },
  {
    category: "handicap_placard_or_jury_excuse",
    label: "Handicap/Jury Excuse",
    confident_match_threshold: 0.95,
    review_threshold: 0.70,
    always_human_review: false,
    route_to_queue: "front_desk",
    splittable: false,
    schema_key: "handicap_placard_or_jury_excuse",
    component_weights: DEFAULT_WEIGHTS,
  },
  {
    category: "payer_correspondence",
    label: "Payer Correspondence",
    confident_match_threshold: 0.99,
    review_threshold: 0.85,
    always_human_review: false,
    route_to_queue: "billing_review",
    splittable: false,
    schema_key: "payer_correspondence",
    component_weights: BILLING_WEIGHTS,
  },
  {
    category: "subpoena_or_legal_notice",
    label: "Subpoena/Legal Notice",
    confident_match_threshold: 1.01,
    review_threshold: 0.70,
    always_human_review: true,
    route_to_queue: "front_desk",
    splittable: false,
    schema_key: "subpoena_or_legal_notice",
    component_weights: DEFAULT_WEIGHTS,
  },
  {
    category: "marketing_or_junk",
    label: "Marketing/Junk",
    confident_match_threshold: 1.01,
    review_threshold: 0.50,
    always_human_review: false,
    route_to_queue: null,
    splittable: false,
    schema_key: "marketing_or_junk",
    component_weights: DEFAULT_WEIGHTS,
  },
  {
    category: "unclassified",
    label: "Unclassified",
    confident_match_threshold: 1.01,
    review_threshold: 0.70,
    always_human_review: true,
    route_to_queue: "front_desk",
    splittable: false,
    schema_key: "unclassified",
    component_weights: DEFAULT_WEIGHTS,
  },
];

/** Legacy short-name → full category name mapping */
const LEGACY_TO_CATEGORY: Record<string, string> = {
  lab: "lab_result",
  imaging: "imaging_report",
  consult: "consult_note",
  referral: "referral_incoming",
  prior_auth: "prior_auth_response",
  dme: "dme_documentation",
  forms: "physical_exam_form",
  records_request: "medical_records_request",
  eob: "eob_era",
  discharge: "hospital_discharge_summary",
  other: "unclassified",
};

/** Find config by category slug — handles both new and legacy names */
export function getCategoryConfig(slug: string): CategoryConfig | undefined {
  return (
    CATEGORY_CONFIG.find((c) => c.category === slug) ??
    CATEGORY_CONFIG.find((c) => c.category === LEGACY_TO_CATEGORY[slug])
  );
}
