/**
 * Full 25-category taxonomy matching the JSON schemas in src/data/schemas/.
 * Short legacy aliases (lab, imaging, etc.) are kept for routing/seed compat.
 */
export const FAX_TYPES = [
  // --- Full schema category names (25) ---
  "lab_result",
  "imaging_report",
  "consult_note",
  "referral_incoming",
  "prior_auth_response",
  "pharmacy_prior_auth_request",
  "pharmacy_refill_request",
  "dme_documentation",
  "physical_exam_form",
  "medical_records_request",
  "eob_era",
  "hospital_discharge_summary",
  "ed_visit_summary",
  "cardiac_diagnostic_report",
  "pathology_report",
  "immunization_record",
  "home_health_order",
  "hospice_correspondence",
  "snf_nh_correspondence",
  "disability_or_leave_form",
  "handicap_placard_or_jury_excuse",
  "payer_correspondence",
  "subpoena_or_legal_notice",
  "marketing_or_junk",
  "unclassified",
  // --- Short legacy aliases (kept for routing/seed compat) ---
  "lab",
  "imaging",
  "consult",
  "referral",
  "prior_auth",
  "dme",
  "forms",
  "records_request",
  "eob",
  "discharge",
  "other",
] as const;

export type FaxType = (typeof FAX_TYPES)[number];

/** Human-readable labels for every type (full + legacy) */
export const FAX_TYPE_LABELS: Record<FaxType, string> = {
  // Full schema categories
  lab_result: "Lab Results",
  imaging_report: "Imaging Report",
  consult_note: "Consult Note",
  referral_incoming: "Incoming Referral",
  prior_auth_response: "Prior Auth Response",
  pharmacy_prior_auth_request: "Pharmacy Prior Auth",
  pharmacy_refill_request: "Rx Refill Request",
  dme_documentation: "DME Documentation",
  physical_exam_form: "Physical Exam Form",
  medical_records_request: "Records Request",
  eob_era: "EOB / ERA",
  hospital_discharge_summary: "Discharge Summary",
  ed_visit_summary: "ED Visit Summary",
  cardiac_diagnostic_report: "Cardiac Diagnostic",
  pathology_report: "Pathology Report",
  immunization_record: "Immunization Record",
  home_health_order: "Home Health Order",
  hospice_correspondence: "Hospice Correspondence",
  snf_nh_correspondence: "SNF/NH Correspondence",
  disability_or_leave_form: "Disability/Leave Form",
  handicap_placard_or_jury_excuse: "Handicap/Jury Excuse",
  payer_correspondence: "Payer Correspondence",
  subpoena_or_legal_notice: "Subpoena/Legal Notice",
  marketing_or_junk: "Marketing/Junk",
  unclassified: "Unclassified",
  // Legacy aliases
  lab: "Lab Results",
  imaging: "Imaging Report",
  consult: "Consult Note",
  referral: "Referral",
  prior_auth: "Prior Auth",
  dme: "DME",
  forms: "Forms",
  records_request: "Records Request",
  eob: "EOB",
  discharge: "Discharge Summary",
  other: "Other",
};

/** Map full schema category name → legacy short name for routing compat */
export const CATEGORY_TO_LEGACY: Record<string, FaxType> = {
  lab_result: "lab",
  imaging_report: "imaging",
  consult_note: "consult",
  referral_incoming: "referral",
  prior_auth_response: "prior_auth",
  pharmacy_prior_auth_request: "prior_auth",
  pharmacy_refill_request: "forms",
  dme_documentation: "dme",
  physical_exam_form: "forms",
  medical_records_request: "records_request",
  eob_era: "eob",
  hospital_discharge_summary: "discharge",
  ed_visit_summary: "discharge",
  cardiac_diagnostic_report: "imaging",
  pathology_report: "lab",
  immunization_record: "forms",
  home_health_order: "dme",
  hospice_correspondence: "other",
  snf_nh_correspondence: "other",
  disability_or_leave_form: "forms",
  handicap_placard_or_jury_excuse: "forms",
  payer_correspondence: "eob",
  subpoena_or_legal_notice: "other",
  marketing_or_junk: "other",
  unclassified: "other",
};

/** All 25 schema category names (no legacy aliases) */
export const SCHEMA_CATEGORIES = [
  "lab_result",
  "imaging_report",
  "consult_note",
  "referral_incoming",
  "prior_auth_response",
  "pharmacy_prior_auth_request",
  "pharmacy_refill_request",
  "dme_documentation",
  "physical_exam_form",
  "medical_records_request",
  "eob_era",
  "hospital_discharge_summary",
  "ed_visit_summary",
  "cardiac_diagnostic_report",
  "pathology_report",
  "immunization_record",
  "home_health_order",
  "hospice_correspondence",
  "snf_nh_correspondence",
  "disability_or_leave_form",
  "handicap_placard_or_jury_excuse",
  "payer_correspondence",
  "subpoena_or_legal_notice",
  "marketing_or_junk",
  "unclassified",
] as const;

export type SchemaCategory = (typeof SCHEMA_CATEGORIES)[number];
